const S=require('../../lib/store'),M=require('../../lib/model'),U=require('../../lib/ui');
const labels={trip:'编辑旅程',moment:'旅行片段',transfer:'交通安排',stay:'住宿安排',activity:'旅途体验',expense:'记一笔',cover:'编辑封面'};
Page({
 data:{keys:['1','2','3','4','5','6','7','8','9','.','0','⌫'],categories:[{id:'food',name:'餐饮',icon:'leaf'},{id:'transport',name:'交通',icon:'car'},{id:'stay',name:'住宿',icon:'bed'},{id:'tickets',name:'门票',icon:'pin'},{id:'shopping',name:'购物',icon:'wallet'},{id:'fun',name:'娱乐',icon:'spark'},{id:'travel',name:'出行',icon:'globe'},{id:'other',name:'其他',icon:'more'}],kind:'moment',form:{},trip:null,people:[],payerIndex:0,types:['支出','收回 AA 款'],typeIndex:0,busy:false,error:'',entry:''},
 onLoad(q){this.importPhotos=q.import==='1';this.tripId=q.trip||'';this.entryId=q.entry||'';U.run(()=>{const t=this.tripId?S.trip(this.tripId):null,kind=q.kind||'moment',today=U.date(),date=q.date||(t?(today>=t.start&&today<=t.end?today:t.start):today);let form={title:'',body:'',date,time:'',photos:[],place:'',from:'',to:'',method:'自驾',checkout:'',note:'',address:''};if(kind==='trip')form=t?M.clone(t):{title:'',start:today,end:today,members:[S.read().profile.name],status:'planned'};else if(kind==='expense')form={name:'',amount:'',date,payer:t.members[0],people:[...t.members],type:'expense'};else if(kind==='cover')form={title:t.title,caption:t.caption||'这一程的回忆',cover:t.cover||''};if(this.entryId){const old=(kind==='expense'?t.expenses:t.entries).find(e=>e.id===this.entryId);if(!old)throw new Error('找不到这条记录');form=M.clone(old);if(kind==='expense')form.amount=M.money(old.cents);}if(q.ai==='1'){const draft=wx.getStorageSync('shiji-ai-draft');if(draft&&draft.kind===kind)Object.assign(form,draft,{date:draft.date||date,photos:[]});wx.removeStorageSync('shiji-ai-draft');}if(kind==='stay'&&!this.entryId&&!form.checkout)form.checkout=new Date(Date.parse(date)+86400000).toISOString().slice(0,10);if(kind==='trip')form.memberText=form.members.join('、');this.setData({pageTitle:kind==='trip'&&!t?'新建旅程':labels[kind],kind,form,trip:t,entry:this.entryId,people:t?t.members.map(name=>({name,checked:(form.people||[]).includes(name)})):[],payerIndex:t?Math.max(0,t.members.indexOf(form.payer)):0,typeIndex:form.type==='collection'?1:0});wx.setNavigationBarTitle({title:labels[kind]});});},
 noop(){},openPeople(){this.setData({peopleOpen:true});},closePeople(){this.setData({peopleOpen:false});},setPayer(e){this.setData({'form.payer':e.currentTarget.dataset.name});},togglePerson(e){const name=e.currentTarget.dataset.name,current=this.data.form.people;const values=this.data.typeIndex===1?(current.includes(name)?[]:[name]):(current.includes(name)?current.filter(n=>n!==name):current.concat(name));this.setData({'form.people':values,people:this.data.people.map(p=>({...p,checked:values.includes(p.name)}))});},setType(e){this.type({detail:{value:e.currentTarget.dataset.index}});},category(e){const c=this.data.categories.find(c=>c.id===e.currentTarget.dataset.id);this.setData({'form.category':c.id,...(!this.data.form.name?{'form.name':c.name}:{})});},amountKey(e){const k=e.currentTarget.dataset.key,v=String(this.data.form.amount||'');let next=k==='⌫'?v.slice(0,-1):k==='.'?(v.includes('.')?v:(v||'0')+'.'):(v==='0'?k:v+k);if(/^\d{0,8}(\.\d{0,2})?$/.test(next))this.setData({'form.amount':next,error:''});},saveMore(){this.more=true;this.save();},
 onReady(){if(this.importPhotos)this.addPhotos();},
 field(e){this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value,error:''});},
 payer(e){this.setData({payerIndex:Number(e.detail.value),'form.payer':this.data.trip.members[Number(e.detail.value)]});},
 type(e){const collection=Number(e.detail.value)===1;this.setData({typeIndex:Number(e.detail.value),'form.type':collection?'collection':'expense','form.people':[] ,people:this.data.people.map(p=>({...p,checked:false}))});},
 people(e){this.setData({'form.people':e.detail.value});},
 async addPhotos(){if(this.data.busy)return;this.setData({busy:true});try{const list=await U.photos(9-this.data.form.photos.length);this.setData({'form.photos':this.data.form.photos.concat(list)});}catch(e){U.error(e);}finally{this.setData({busy:false});}},
 removePhoto(e){this.setData({'form.photos':this.data.form.photos.filter((_,i)=>i!==Number(e.currentTarget.dataset.index))});},
 async cover(){if(this.data.busy)return;this.setData({busy:true});try{const photos=await U.photos(1);if(photos[0])this.setData({'form.cover':photos[0]});}catch(e){U.error(e);}finally{this.setData({busy:false});}},
 save(){if(this.data.busy)return;this.setData({busy:true,error:''});try{const f=M.clone(this.data.form),kind=this.data.kind;
  if(kind==='trip'){f.title=f.title.trim();f.members=[...new Set(f.memberText.split(/[、,，\n]/).map(s=>s.trim()).filter(Boolean))];delete f.memberText;M.validateTrip(f);if(this.tripId){S.edit(this.tripId,t=>{if(t.expenses.some(e=>!f.members.includes(e.payer)||e.people.some(m=>!f.members.includes(m))))throw new Error('同行人关联了账目，请先调整账目再移除');if(t.entries.some(e=>e.date<f.start||e.date>f.end))throw new Error('已有记录在新日期范围之外，请先调整记录日期');Object.assign(t,{title:f.title,start:f.start,end:f.end,members:f.members});});}else{const id=M.id();S.update(s=>s.trips.push({...f,id,checks:[],entries:[],expenses:[],diary:'',mood:'',font:'hand',cover:'',caption:''}));wx.redirectTo({url:'/pages/trip/trip?id='+id});return;}}
  else if(kind==='cover'){if(!f.title.trim())throw new Error('请填写旅程名称');S.edit(this.tripId,t=>Object.assign(t,{title:f.title.trim(),cover:f.cover,caption:f.caption}));}
  else if(kind==='expense'){if(!/^\d+(\.\d{1,2})?$/.test(String(f.amount)))throw new Error('金额最多保留两位小数');f.cents=Math.round(Number(f.amount)*100);f.id=this.entryId||M.id();S.edit(this.tripId,t=>{M.validateExpense(f,t);const i=t.expenses.findIndex(e=>e.id===f.id);if(i<0)t.expenses.push(f);else t.expenses[i]=f;});}
  else {f.kind=kind;f.id=this.entryId||M.id();S.edit(this.tripId,t=>{M.validateEntry(f,t);const i=t.entries.findIndex(e=>e.id===f.id);if(i<0)t.entries.push(f);else t.entries[i]=f;});}
  if(this.more&&kind==='expense'){this.setData({'form.name':'','form.amount':'','form.category':'',entry:''});this.entryId='';wx.showToast({title:'已保存',icon:'success'});}else wx.navigateBack();
 }catch(e){this.setData({error:e.message||'保存失败，请检查本地存储空间后重试。'});}finally{this.more=false;this.setData({busy:false});}},
 remove(){wx.showModal({title:'删除这条记录？',content:'删除后将从本段旅程移除。',confirmColor:'#9b4f40',success:r=>{if(r.confirm)U.run(()=>{S.edit(this.tripId,t=>{const key=this.data.kind==='expense'?'expenses':'entries';t[key]=t[key].filter(e=>e.id!==this.entryId);});wx.navigateBack();});}});}
});
