const S=require('../../lib/store'),M=require('../../lib/model'),U=require('../../lib/ui');
Page({
 data:{memoryYear:'全部年份',memoryMonth:'全部月份',filterOpen:false,top:44,section:'home',trips:[],profile:{},count:0,photos:0},
 onLoad(){const info=wx.getWindowInfo();this.setData({top:info.statusBarHeight||44});},
 onShow(){this.refresh();},
 refresh(){U.run(()=>{const s=S.read();this.setData({profile:s.profile,trips:s.trips.map(t=>({...t,range:t.start.replace(/-/g,'.')+' — '+t.end.slice(5).replace('-','.'),companion:t.members[1]||'',companionShort:t.members[1]?.slice(-1)||'',days:M.dates(t.start,t.end).length,progress:t.checks.length?Math.round(t.checks.filter(c=>c.done).length/t.checks.length*100):0,statusLabel:{active:'正在旅途中',planned:'下一次出发',past:'这一程的回忆'}[t.status]})),count:s.trips.length,activeId:s.trips.find(t=>t.status==='active')?.id||'',nextId:s.trips.find(t=>t.status==='planned')?.id||'',moments:s.trips.reduce((n,t)=>n+t.entries.filter(e=>e.kind==='moment').length,0),journals:s.trips.filter(t=>t.status==='past').length,photos:s.trips.reduce((n,t)=>n+t.entries.reduce((a,e)=>a+(e.photos||[]).length,0),0)});this.filterMemories();});},
 filterMemories(){const all=this.data.trips.filter(t=>t.status==='past'),year=this.data.memoryYear,month=this.data.memoryMonth;this.setData({monthCells:Array.from({length:12},(_,i)=>({label:(i+1)+'月',count:all.filter(t=>(year==='全部年份'||t.start.slice(0,4)===year)&&Number(t.start.slice(5,7))===i+1).length})),memoryTrips:all.filter(t=>(year==='全部年份'||t.start.slice(0,4)===year)&&(month==='全部月份'||Number(t.start.slice(5,7))===Number(month.slice(0,-1)))).map(t=>({...t,momentCount:t.entries.filter(e=>e.kind==='moment').length})),years:['全部年份',...Array.from(new Set(all.map(t=>t.start.slice(0,4)))).sort().reverse()],months:['全部月份',...Array.from({length:12},(_,i)=>(i+1)+'月')],filterLabel:year==='全部年份'&&month==='全部月份'?'全部时间':[year,month].filter(v=>!v.startsWith('全部')).join(' · ')});},
 chooseYear(e){this.setData({memoryYear:e.currentTarget.dataset.value});this.filterMemories();},chooseMonth(e){this.setData({memoryMonth:e.currentTarget.dataset.value});this.filterMemories();},allMonths(){this.setData({memoryMonth:'全部月份'});this.filterMemories();},
 openFilter(){this.setData({filterOpen:true});},closeFilter(){this.setData({filterOpen:false});},noop(){},
 filterYear(e){this.setData({memoryYear:this.data.years[Number(e.detail.value)]});this.filterMemories();},
 filterMonth(e){this.setData({memoryMonth:this.data.months[Number(e.detail.value)]});this.filterMemories();},
 resetFilter(){this.setData({memoryYear:'全部年份',memoryMonth:'全部月份'});this.filterMemories();},
 memories(){this.setData({section:'memories'});wx.pageScrollTo({scrollTop:0,duration:0});},
 importPhotos(){U.go('import');},
 companions(){const names=[...new Set(this.data.trips.flatMap(t=>t.members))].filter(n=>n!==this.data.profile.name);wx.showModal({title:'同行的人',content:names.length?names.join('、'):'还没有同行人。在编辑旅程中可以添加。',showCancel:false});},
 privacy(){wx.showModal({title:'隐私与分享',content:'当前记录仅保存在本机，没有公开分享。',showCancel:false});},
 language(){wx.showModal({title:'语言 / Language',content:'当前小程序体验版支持简体中文。',showCancel:false});},
 editBio(){wx.showModal({title:'个人签名',editable:true,content:this.data.profile.bio||'',success:r=>{if(r.confirm)U.run(()=>{S.update(s=>{s.profile.bio=r.content.trim();});this.refresh();});}});},
 async avatar(){try{const photos=await U.photos(1);if(photos.length){S.update(s=>{s.profile.avatar=photos[0];});this.refresh();}}catch(e){U.error(e);}},
 tab(e){this.setData({section:e.currentTarget.dataset.id});wx.pageScrollTo({scrollTop:0,duration:0});},
 open(e){U.go('trip',{id:e.currentTarget.dataset.id});},
 prepare(){if(this.data.activeId)U.go('notebook',{trip:this.data.activeId,kind:'checks'});},
 assistant(){U.go('assistant',{trip:this.data.activeId||this.data.trips[0]?.id||''});},
 sync(){U.go('sync');},
 create(){U.go('editor',{kind:'trip'});},
 record(e){U.go('editor',{kind:'moment',trip:e.currentTarget.dataset.id});},
 profile(){wx.showModal({title:'你的昵称',editable:true,placeholderText:'写下昵称',content:this.data.profile.name,success:r=>{if(r.confirm&&r.content.trim())U.run(()=>{S.update(s=>{const old=s.profile.name,name=r.content.trim();if(s.trips.some(t=>t.members.includes(name)&&name!==old))throw new Error('昵称与同行人重名');s.profile.name=name;s.trips.forEach(t=>{t.members=t.members.map(m=>m===old?name:m);t.expenses.forEach(e=>{if(e.payer===old)e.payer=name;e.people=e.people.map(m=>m===old?name:m);});});});this.refresh();});}});},
 about(){wx.showModal({title:'拾迹 · 本地体验版',content:'记录保存在当前微信的小程序本地空间，尚未接入云同步。清除小程序数据可能导致记录丢失。AI 与 OCR 尚未接入。',showCancel:false});}
});
